version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
      - $HOME/.poetry/bin/poetry config virtualenvs.create false
      - $HOME/.poetry/bin/poetry install

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
