version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin/:$PATH"
    - poetry config virtualenvs.create false
    - poetry install
    - cd docs && make html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
